# Generated by Django 4.1.1 on 2022-11-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('deploy_date', models.DateTimeField(auto_now_add=True, verbose_name='date deployed')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versiontracker.appenvironment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versiontracker.appname')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('appversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='versiontracker.appversion')),
            ],
            bases=('versiontracker.appversion',),
        ),
    ]
